stages:
  - build
  - deploy
  
services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD  $CI_REGISTRY  

build-docs:
  stage: build
  script:
    - docker build -t gitlabnew.techwave.net:5050/fintrust/wiki -f Dockerfile .
    - docker push gitlabnew.techwave.net:5050/fintrust/wiki
    - echo "pushed successfully!!!!"
  tags:
    - docker

deploy-docs:
  stage: deploy
  script:
    - docker rm -f fintrust-wiki
    - docker run -d -p 8080:8080 --name="fintrust-wiki" gitlabnew.techwave.net:5050/fintrust/wiki      
  tags:
    - docker

after_script:
  - docker logout 

 




 


